### ISSUE TITLE
Hintergrundfarbe und Stiftbreite nicht konfigurierbar

### ISSUE THREAD

**Issue by minstyle** [do-while/contao-signature-formfield-bundle#6]
**Contao 4.13.30
PHP 8.1
do-while/contao-signature-formfield-bundle 1.0.2**

Unter den `Experteneinstellungen` werden die Eingaben von `Hintergrundfarbe` und `Stiftbreite` nicht im Frontend berücksichtigt.

Screenshots:

![grafik](https://github.com/do-while/contao-signature-formfield-bundle/assets/2649562/f7e68ae8-09d9-4eb3-83ec-3e58c61a99be)

Ausgabe im Frontend:

![grafik](https://github.com/do-while/contao-signature-formfield-bundle/assets/2649562/7d2b8c38-8f12-4630-9a00-fa3ba74aa4a9)

Bei dem Inline CSS ist `background-color:#transparent;` auch nicht W3C-valide.

**Comment by do-while** [comment]
Alles klar, Fehler sind beseitigt. Ist dann wohl sonst noch niemandem aufgefallen.
Neues Release: 1.0.3

**Comment by minstyle** [comment]
Funktioniert jetzt. Ich danke dir für den schnellen Fix 👌
